programs/avocado: initial support to run avocado-vt tests
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/avocado/run b/programs/avocado/run
--- a/programs/avocado/run
+++ b/programs/avocado/run
@@ -1,65 +1,83 @@
 #!/bin/bash
-# - test_group
+# - group
 
 . $LKP_SRC/lib/reproduce-log.sh
 . $LKP_SRC/lib/debug.sh
 . $LKP_SRC/lib/env.sh
 . $LKP_SRC/lib/upload.sh
 
-tmp_avocado="/tmp/avocado"
+avocado_conf_file="/etc/avocado/avocado.conf"
+avocado_data_dir="/lkp/benchmarks/avocado/data"
+avocado_result_dir="/tmp/avocado/result"
 
-set_conf()
+setup_conf()
 {
-	[ -d "/etc/acocado" ] || log_cmd mkdir -p "/etc/avocado"
-	local conf_file="/etc/avocado/avocado.conf"
-	[ -d "$tmp_avocado/result" ] || log_cmd mkdir -p "$tmp_avocado/result"
-	[ -d "$tmp_avocado/data" ] || log_cmd mkdir -p "$tmp_avocado/data"
+	[[ -f $avocado_conf_file ]] || return
 
-	## Set avocado config file, specify those 4 important dir.
-	## After test finished, upload $tmp_avocado to cluster.
-	## $tmp_avocado includes all testting info.
-	## Set test_dir to get all available tests by avocado list.
-	cat <<EOT >> $conf_file
-[datadir.paths]
-base_dir = $tmp_avocado
-test_dir = $BENCHMARK_ROOT/avocado/examples/tests
-data_dir = $tmp_avocado/data
-logs_dir = $tmp_avocado/result
+	log_cmd mkdir -p "$avocado_result_dir" || return
+
+	# After test finished, upload $base_dir which includes all testting info.
+	cat <<EOT >> $avocado_conf_file
+logs_dir = $avocado_result_dir
 EOT
-}
-
-get_test()
-{
-	## avocado list will list all available tests
-	log_cmd avocado list $BENCHMARK_ROOT/avocado/examples/tests >> /tmp/all_tests
-	## There are two type tests: INSTRUMENTED and SIMPLE.
-	## Don't test SIMPLE, all_tests will be splited.
-	log_cmd sed -i "/^SIMPLE/d" /tmp/all_tests
-	## Format all_test.
-	## Before: INSTRUMENTED /lkp/benchmarks/avocado/examples/tests/abort.py:AbortTest.test
-	## After: /lkp/benchmarks/avocado/examples/tests/abort.py:AbortTest.test
-	gawk '{print $2 > "/tmp/all_test"}' /tmp/all_tests
-}
-
-split_test()
-{
-	## split all tests, each group has 20 tests.
-	## e.g. split -l 20 all_test -d -a 2 group_
-	## get group_00  group_01  group_02
-	log_cmd split -l 20 /tmp/all_test -d -a 2 group_
 }
 
 run_test()
 {
-	while read line
-	do
-		log_cmd avocado run $line --job-timeout 30 2>&1
-	done < $test_group
+	echo "$group total tests $(avocado list | grep \.$group\. | wc -l)"
+	# avocado-vt type_specific.io-github-autotest-qemu.blockdev_commit_backing_file
+	# avocado-vt io-github-autotest-qemu.vlan.vlan_connective_test
+	# avocado-vt type_specific.lkvs.boot_check.vm.16G.208_cpu
+	local test
+	log_cmd avocado list | grep \.$group\. | cut -d' ' -f2 | while read test; do
+		log_cmd avocado run $test 2>&1
+	done
 }
 
-set_conf || die "Failed to set config file"
-get_test || die "Failed to get all available tests"
-split_test || die "Failed to split tests into test_group"
-run_test
+setup_env()
+{
+	# required for lkvs
+	lsmod | grep tun || modprobe tun
 
-upload_files -t results $tmp_avocado/*
+	# resolve libvirtd service issue
+	# 	libvirtd[9640]: libvirt version: 9.0.0, package: 9.0.0-4+deb12u1 (Debian)
+	# 	libvirtd[9640]: invalid argument: Failed to parse user 'libvirt-qemu'
+	# 	libvirtd[9640]: Initialization of QEMU state driver failed: invalid argument: Failed to parse user 'libvirt-qemu'
+	#	libvirtd[9640]: Driver state initialization failed
+	addgroup --system libvirt-qemu
+	adduser --system --ingroup libvirt-qemu --home /var/lib/libvirt --no-create-home --shell /bin/false libvirt-qemu
+
+	log_cmd systemctl restart libvirtd || return
+	sleep 120
+	log_cmd systemctl status libvirtd
+
+	# create virbr0 interface that is a virtual network bridge
+	log_cmd virsh net-define /usr/share/libvirt/networks/default.xml || return
+	log_cmd virsh net-start default
+}
+
+install_lkvs_tests()
+{
+	cat <<EOT > $avocado_data_dir/avocado-vt/virttest/test-providers.d/lkvs.ini
+[provider]
+uri: file:///lkp/benchmarks/lkvs
+
+[qemu]
+subdir: KVM/qemu
+EOT
+
+	# to install the lkvs tests actually
+	log_cmd avocado vt-bootstrap --vt-no-downloads --vt-type qemu
+
+	avocado list | grep $group | sort > $avocado_result_dir/tests
+}
+
+setup_conf || die "failed to setup config file"
+setup_env || die "failed to setup env"
+
+# this could be run setup_env
+[[ $group = lkvs ]] && install_lkvs_tests
+
+run_test || die "failed to run test"
+
+upload_files -t results $avocado_result_dir/*
