lkp-exec/install: return success for makepkg_install_benchmark() when pkg is not adapted
This restores the behavior to continue build_install_benchmarks() when
adaptation-pkg doesn't contain pkg.

Fixes: 49c30a6cc6d6 ("lkp-exec/install: stop when makepkg_install_benchmark() fails")
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/lkp-exec/install b/lkp-exec/install
--- a/lkp-exec/install
+++ b/lkp-exec/install
@@ -197,14 +197,11 @@ makepkg_install_benchmark() {
 	local pkg=$1
 	local distro=$2
 
-	if grep -w "^$pkg:" "$LKP_SRC/distro/adaptation-pkg/$distro"; then
-		makepkg_install "$pkg" && return
+	grep -w "^$pkg:" "$LKP_SRC/distro/adaptation-pkg/$distro" || return 0
 
-		echo "Install $pkg failed"
-	else
-		echo "Cannot find $pkg in $LKP_SRC/distro/adaptation-pkg/$distro"
-	fi
+	makepkg_install "$pkg" && return
 
+	echo "Install $pkg failed"
 	return 1
 }
 
